# If you want to run a local instance with redis, you can use this directly, but
# it's probably better to use:
#     ./scripts/run-development-server.sh --with-redis
#

version: '3'
services:
  app:
    env_file:
      - ${PWD}/husky_directory/settings/compose-with-redis.dotenv
    build:
      dockerfile: Dockerfile
      context: ..
      target: development-server
    ports: ["8000:8000"]
    command: >
      poetry run gunicorn -b 0.0.0.0:8000
      -c "/app/husky_directory/gunicorn.conf.py"
      "husky_directory.app:create_app()"
    volumes:
      - ${UWCA_CERT_PATH}:/app/certificates:ro
      - ${PWD}/husky_directory:/app/husky_directory
  redis:
    image: redis:latest
    command: redis-server --user uw-directory on +@all -@dangerous ~uw-directory:* >supersecret
    ports:
      - "6379:6379"
  prometheus:
    image: prom/prometheus:latest
    restart: always
    ports:
      - 9000:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ${PWD}/docker/prometheus:/etc/prometheus/
