base: &base
  version: 1
  formatters:
    default:
      format: "[%(levelname)s][%(asctime)s][%(module)s]: %(message)s"
  handlers:
    wsgi:
      level: DEBUG
      class: logging.StreamHandler
      formatter: default
  loggers:
    glogging:
      level: WARNING  # This is very noisy and duplicates a lot of error messages.
    gunicorn.error:
      level: DEBUG
      handlers:
        - wsgi

development: *base

test: *base

production:
  <<: *base
  root:
    level: INFO
    handlers:
      - wsgi
