base: &base
  version: 1
  formatters:
    default:
      # TODO: For some reason this formatter isn't being used. We need to
      #       fix this so that we know we can control the log formatting easily.
      format: "[%(asctime)s] %(levelname)s in %(module)s: %(message)s"
  handlers:
    wsgi:
      level: DEBUG
      class: logging.StreamHandler
      formatter: default
  loggers:
    root:
      level: DEBUG
      handlers:
        - wsgi

development: *base

test: *base

production:
  <<: *base
  root:
    level: INFO
    handlers:
      - wsgi
