base: &base
  version: 1
  formatters:
    default:
      format: "[%(asctime)s] %(levelname)s in %(module)s: %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: default
    wsgi:
      level: DEBUG
      class: logging.StreamHandler
      formatter: default
  loggers:
    root:
      level: DEBUG
      handlers:
        - wsgi
        - console

development: *base
production:
  <<: *base
  root:
    level: INFO
    handlers:
      - wsgi
