base: &base
  version: 1
  formatters:
    default:
      format: "[%(levelname)s][%(asctime)s][%(module)s]: %(message)s"
    json:
      '()': husky_directory.logging.JsonFormatter
  handlers:
    wsgi:
      level: INFO
      class: logging.StreamHandler
      formatter: json
  loggers:
    glogging:
      # Turn off all but critical `glogging` messages, because it's
      # a very noisy module that is out of our control.
      level: CRITICAL
      propagate: true
    app:
      level: DEBUG
      propagate: true
    gunicorn.error:
      handlers:
        - wsgi

development: *base

test: *base

production:
  <<: *base
  root:
    level: INFO
    handlers:
      - wsgi
