on:
  push:
    branches:
      - main
      - dry-run-create-release

env:
  STEP_SCRIPTS: ${{ github.workspace }}/.github/steps/create-release

jobs:
  configure-release:
    runs-on: ubuntu-latest
    outputs:
      release-required: ${{ steps.get-release.outputs.release-required }}
      version: ${{ steps.get-release.outputs.version }}
      latest-release: ${{ steps.get-release.outputs.latest-release }}
    steps:
      - uses: actions/checkout@v2
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.1.0
      - run: ./scripts/install-build-scripts.sh
      - run: ${STEP_SCRIPTS}/is-release-required.sh
        id: get-release
        name: Get version and determine release requirement

  create-release:
    permissions:
      contents: write
      id-token: write
    if: needs.configure-release.outputs.release-required == 'true'
    needs: [configure-release]
    env:
      version: ${{ needs.configure-release.outputs.version }}
    runs-on: ubuntu-latest
    outputs:
      version: ${{ needs.configure-release.outputs.version }}
    concurrency:
      group: ${{ github.repository }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v2
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.1.0
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCR_TOKEN }}
        name: Authenticate to gcloud
      - uses: google-github-actions/setup-gcloud@v0
        with:
          # This version has to stay pinned in order
          # to work with docker-compose; there is a bug
          # either in Docker's or Google's software.
          # Ref: https://stackoverflow.com/questions/65295958/docker-compose-not-working-with-gcloud-cannot-find-openssl
          version: 297.0.1

      - run: |
          poetry run pip install tox uw-it-build-fingerprinter

      - run: ./scripts/install-build-scripts.sh
        name: Install UWIT-IAM/common-build-scripts

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.1.0

      - run: |
          poetry run pip install tox uw-it-build-fingerprinter
          gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS}
          gcloud auth configure-docker --quiet gcr.io
      - run: |
          poetry run tox -e build-layers -- -k
          poetry run tox -e unit-tests
        name: Validate build

      - name: Push release image
        env:
          release_layer: gcr.io/uwit-mci-iam/husky-directory.app:${{ env.version }}
          release_image: gcr.io/uwit-mci-iam/husky-directory:${{ env.version }}
        run: |
          set -x
          gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS}
          ./scripts/build-layers.sh -k -t ${{ env.version }} --cache
          docker tag ${{ env.release_layer }} ${{ env.release_image }}
          if [[ "${{ github.ref }}" == 'refs/heads/main' ]]
          then
            docker push ${{ env.release_image }}
          fi

      - name: Create release ${{ needs.configure-release.outputs.version }}
        uses: ncipollo/release-action@v1
        with:
          # Use PAT so that the release will trigger the deployment workflow.
          token: ${{ secrets.ACTIONS_PAT }}
          tag: ${{ needs.configure-release.outputs.version }}
        if: github.ref == 'refs/heads/main'
