name: Pull request validation workflow

on:
  pull_request:
    paths-ignore:
      - '*.md'
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled

env:
  GCR_TOKEN: ${{ secrets.GCR_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  STEP_SCRIPTS: ${{ github.workspace }}/.github/steps/pull-request

jobs:
  update-pr-branch-version:
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.update-version.outputs.new-version }}
    steps:
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2.1.0
      - uses: uwit-iam/actions/require-semver-guidance-label@0.1.4
        id: guidance
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - run: echo ::set-output name=version::$(poetry version -s)
        id: get-version
      - uses: actions/checkout@v2
      - name: Update PR version to base_version+guidance
        env:
          BASE_VERSION: ${{ steps.get-version.outputs.version }}
        run: |
          set -x
          poetry version $BASE_VERSION
          poetry version ${{ steps.guidance.outputs.guidance }}
          if [[ -n "$(git diff)" ]]
          then
            new_version=$(poetry version -s)
            echo ::set-output name=new-version::$new_version
          fi
        id: update-version
      - if: steps.update-version.outputs.new-version
        uses: EndBug/add-and-commit@v7.2.1
        env:
          version: ${{ steps.update-version.outputs.new-version }}
        with:
          add: pyproject.toml
          default_author: github_actions
          push: true
          message: "[Bot] Update version to ${{ env.version }}"
  validate-image-quality:
    needs: [update-pr-branch-version]
    runs-on: ubuntu-latest
    env:
      BUILD_SCRIPTS_DIR: /tmp/build-scripts
      APP_VERSION: ${{ needs.update-pr-branch-version.outputs.new-version }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          ./.github/scripts/gcr-login.sh
          ./.github/scripts/install-build-scripts.sh
        id: configure
      - name: Run validation checks and tests
        run: ./scripts/pre-push.sh --headless --version $APP_VERSION
        id: run-validations
      - name: Push tag for pull request
        run: ${STEP_SCRIPTS}/create-pr-tag.sh -s ${{ steps.run-validations.outputs.image }}
        id: create-pr-tag
      - uses: mshick/add-pr-comment@v1
        env:
          PR_TAG: ${{ steps.create-pr-tag.outputs.image }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          allow-repeats: false
          message: |
            Download and run the latest build with:

            ```
            ./scripts/run-development-server.sh -i ${{ env.PR_TAG }}
            ```
