name: "Run 'poetry update' and create a PR"

on:
  push:
    branches:
      - run-poetry-update-workflow
  schedule:
    - cron: '0 0 * * MON'
  workflow_dispatch:

jobs:
  task:
    permissions:
      contents: write
      pull-requests: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: abatilo/actions-poetry@v2.1.6
      - uses: UWIT-IAM/actions/configure-gcloud-docker@0.1
        with:
          gcloud-token: ${{ secrets.GCR_TOKEN }}
      - run: sudo apt-get -y install jq
      - run: poetry update --lock
        id: poetry-update
      - run: poetry run tox
        name: Validate dependency updates
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.14.0
        with:
          add-paths: poetry.lock
          commit-message: ${{ env.message }}
          delete-branch: true
          title: ${{ env.message }}
          assignees: goulter,jdiverp
          reviewers: goulter,jdiverp
          labels: semver-guidance:patch
        env:
          message: '[bot] patch dependencies'
