name: "Run 'poetry update' and create a PR"

on:
  push:
    branches:
      - run-poetry-update-workflow
  schedule:
    - cron: '0 0 * * MON'
  workflow_dispatch:

jobs:
  task:
    permissions:
      contents: write
      pull-requests: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: abatilo/actions-poetry@v2.1.3

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCR_TOKEN }}
        name: Authenticate to gcloud
      - uses: google-github-actions/setup-gcloud@v0
        with:
          # This version has to stay pinned in order
          # to work with docker-compose; there is a bug
          # either in Docker's or Google's software.
          # Ref: https://stackoverflow.com/questions/65295958/docker-compose-not-working-with-gcloud-cannot-find-openssl
          version: 297.0.1
      - run: gcloud auth configure-docker gcr.io
      - run: poetry update
        id: poetry-update
      - run: poetry run tox
        name: Validate dependency updates
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.14.0
        with:
          add-paths: poetry.lock
          commit-message: ${{ env.message }}
          delete-branch: true
          title: ${{ env.message }}
          assignees: tomthorogood
          reviewers: tomthorogood
          labels: semver-guidance:patch
        env:
          message: '[bot] patch dependencies'
