name: Weekly uw-husky-directory scheduled maintenance

on:
# schedule:
#   - cron: '0 4 * * 1'  # Run at 4am (UTC) every Monday.
  push:
    # This supports the ability to force push to run for testing purposes,
    # or if you want to force a rebuild for any reason! Go for it!
    branches:
      - run-scheduled-maintenance-workflow

env:
  SLACK_BOT_TOKEN: ${{ secrets.ACTIONS_SLACK_BOT_TOKEN }}
  BASE_IMAGE_REPO: gcr.io/${{ secrets.IAM_GCR_REPO }}/husky-directory-base
  APP_IMAGE_REPO: gcr.io/${{ secrets.IAM_GCR_REPO }}/husky-directory
  SLACK_CHANNEL: '#cloud-native-directory'
  STEP_SCRIPTS: ./.github/steps/scheduled-maintenance
  BUILD_SCRIPTS_DIR: /tmp/build-scripts
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_URL_BASE: https://github.com/${{ github.repository }}/pull

jobs:
  scheduled-maintenance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - if: github.event_name != 'schedule'
        run: echo "POETRY_VERSION_GUIDANCE=prerelease" >> $GITHUB_ENV
        name: Update version guidance

      - name: Bootstrap Google Cloud
        with:
          project_id: ${{ secrets.IAM_GCR_REPO }}
          service_account_key: ${{ secrets.GCR_TOKEN }}
          export_default_credentials: true
          credentials_file_path: ${{ github.workspace }}/gcloud-credentials.json
        uses: google-github-actions/setup-gcloud@v0.2.1

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.0

      - name: Configure build
        run: $STEP_SCRIPTS/configure-environment.sh
        id: configure

      - uses: uwit-iam/actions/update-slack-workflow-canvas@0.1.1
        with:
          command: create-canvas
          json: ${{ steps.configure.outputs.workflow-json }}
        id: create-canvas
        name: Create slack notification

      - run: |
          echo "SLACK_CANVAS_ID=${{ steps.create-canvas.outputs.canvas-id }}" >> $GITHUB_ENV
          echo "ACTIVE_STEP=configure" >> $GITHUB_ENV
          echo "NEXT_STEP=rebuild-images" >> $GITHUB_ENV
        name: Export slack notification state variables

      - uses: uwit-iam/actions/update-slack-workflow-canvas@0.1.1
        with:
          command: add-artifact
          description: >
            <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            | workflow execution> triggered by '${{ github.event_name }}' event.
        name: Add execution information to slack

      - uses: uwit-iam/actions/update-slack-workflow-canvas@0.1.1
        with:
          command: update-workflow
          step-id: ${{ env.ACTIVE_STEP }}, ${{ env.NEXT_STEP }}
          step-status: succeeded, in progress
        if: steps.create-canvas.outputs.canvas-id
        name: Update workflow status
      - run: |
          echo "ACTIVE_STEP=$NEXT_STEP" >> $GITHUB_ENV
          echo "NEXT_STEP=test-application-image" >> $GITHUB_ENV
        name: Advance workflow to next step

      - run: |
          $STEP_SCRIPTS/update-dependency-image.sh
          $STEP_SCRIPTS/update-application-image.sh
        name: Build new images

      - uses: uwit-iam/actions/update-slack-workflow-canvas@0.1.1
        with:
          command: update-workflow
          step-id: ${{ env.ACTIVE_STEP }}, ${{ env.NEXT_STEP }}
          step-status: succeeded, in progress
        if: steps.create-canvas.outputs.canvas-id
        name: Update workflow status

      - run: |
          echo "ACTIVE_STEP=$NEXT_STEP" >> $GITHUB_ENV
          echo "NEXT_STEP=push-poetry-lock" >> $GITHUB_ENV
        name: Advance workflow to next step

      - run: ./scripts/run-image-tests.sh -i $APP_IMAGE_REPO:$new_version --headless
        env:
          new_version: ${{ steps.configure.outputs.new-app-version }}
        name: Run tests

      - uses: uwit-iam/actions/update-slack-workflow-canvas@0.1.1
        with:
          command: update-workflow
          step-id: ${{ env.ACTIVE_STEP }}, ${{ env.NEXT_STEP }}
          step-status: succeeded, in progress
        if: steps.create-canvas.outputs.canvas-id
        name: Update workflow status

      - run: |
          echo "ACTIVE_STEP=$NEXT_STEP" >> $GITHUB_ENV
          echo "NEXT_STEP=push-di-fingerprint" >> $GITHUB_ENV
        name: Advance workflow to next step

      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.2.1
        env:
          git_tag: ${{ github.event_name == 'schedule' && steps.configure.outputs.new-app-version || '0.0.0-testing --force'}}
        with:
          add: 'pyproject.toml poetry.lock'
          default_author: github_actions
          pull_strategy: 'NO-PULL'
          tag: ${{ env.git_tag }}

      - name: create pull request
        run: ${STEP_SCRIPTS}/create-pull-request.sh
        id: create-pull-request

      - run: ${STEP_SCRIPTS}/create-build-artifact.sh
        id: create-artifact
        env:
          GITHUB_PR_NUMBER: ${{ steps.create-pull-request.outputs.pull-request-number }}

      - uses: uwit-iam/actions/update-slack-workflow-canvas@0.1.1
        if: steps.create-canvas.outputs.canvas-id
        with:
          command: add-artifact
          description: ${{ steps.create-artifact.outputs.slack-artifact }}
        name: Add notification artifact

      - uses: uwit-iam/actions/update-slack-workflow-canvas@0.1.1
        with:
          command: update-workflow
          step-id: ${{ env.ACTIVE_STEP }}, ${{ env.NEXT_STEP }}
          step-status: succeeded, in progress
        if: steps.create-canvas.outputs.canvas-id
        name: Update workflow status

      - run: |
          echo "ACTIVE_STEP=$NEXT_STEP" >> $GITHUB_ENV
          docker tag $BASE_IMAGE_REPO:$fingerprint $BASE_IMAGE_REPO:$new_di_version
          docker push $BASE_IMAGE_REPO:$fingerprint
          docker push $BASE_IMAGE_REPO:$new_di_version
          docker push $APP_IMAGE_REPO:$new_app_version
        name: Push images
        env:
          fingerprint: ${{ steps.configure.outputs.di-fingerprint }}
          new_di_version: ${{ steps.configure.outputs.new-di-version }}
          new_app_version: ${{ steps.configure.outputs.new-app-version }}
      - uses: uwit-iam/actions/update-slack-workflow-canvas@0.1.1
        with:
          command: update-workflow
          step-id: ${{ env.ACTIVE_STEP }}
          step-status: succeeded
        if: steps.create-canvas.outputs.canvas-id
        name: Update workflow status

      # Everything after this is the epilogue that cleans up the workflow
      - if: failure() && steps.create-canvas.outputs.canvas-id
        with:
          command: update-workflow
          step-id: ${{ env.ACTIVE_STEP }}
          step-status: failed
          workflow-status: failed
        uses: uwit-iam/actions/update-slack-workflow-canvas@0.1.1
        name: Mark workflow as failed

      - with:
          command: update-workflow
          workflow-status: succeeded
        uses: uwit-iam/actions/update-slack-workflow-canvas@0.1.1
        if: success() && steps.create-canvas.outputs.canvas-id
        name: Mark workflow as succeeded

      - if: always() && steps.create-canvas.outputs.canvas-id
        with:
          command: remove-step
          step-id: '*'
          step-status: succeeded
        uses: uwit-iam/actions/update-slack-workflow-canvas@0.1.1
        name: Clean up successful steps

      - if: always() && steps.create-canvas.outputs.canvas-id
        with:
          command: finalize-workflow
        uses: uwit-iam/actions/update-slack-workflow-canvas@0.1.1
        name: Finalize workflow
